### ISSUE TITLE
Combine coverage comments into one summary comment

### ISSUE THREAD

**Issue by emgrav** [famedly/Meow-Coverage#55]
Right now the coverage comments can be quite spammy. We should combine it all into a single comment.

**Comment by tlater-famedly** [comment]
This off-the-shelf action just does everything meow does, then: https://github.com/marketplace/actions/report-lcov

**Comment by tlater-famedly** [comment]
Seems to work pretty well: https://github.com/famedly/ldap-sync/pull/34#issuecomment-2288552637

We'd like to combine this with [our review app](https://github.com/famedly/frontend-ci-templates/blob/main/.github/workflows/review-app.yml), but we need to make the SSH key for publishing those pages available to do so.
